name: Deploy to QA on Merge

on:
  push:
    branches: [development]
    paths: ['force-app/**']

jobs:
  deploy:
    permissions:
      contents: read
      pull-requests: read
    uses: bes-innovation/gmd-seed-gh-workflow/.github/workflows/gmd-seed-wfl-sf-deploy.yml@v1
    with:
      environment: qa
      target-org: qa
    secrets: inherit
