name: PR Validation on QA

on:
  pull_request:
    branches: [development]
    paths: ['force-app/**']

jobs:
  validate:
    uses: bes-innovation/gmd-seed-gh-workflow/.github/workflows/gmd-seed-sf-validate-wfl.yml@v1
    with:
      environment: qa
      target-org: qa
      severity-threshold: "5"
    secrets: inherit
